server:
  port: 80
spring:
  application:
    name: cloud-order-server
eureka:
  client:
    # 不注册自己
    register-with-eureka: true
    # 表示自己是注册中心，不用检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-order-server
    prefer-ip-address: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000