server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # 不注册自己
    register-with-eureka: false
    # 表示自己是注册中心，不用检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    #关闭自我自我保护机制
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000